# Generated by Django 5.1 on 2024-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_word_created_at_word_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=48)),
                ('meaning', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='word',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
