# Generated by Django 5.1 on 2024-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_translation_alter_word_meaning_alter_word_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='meaning',
        ),
        migrations.AddField(
            model_name='translation',
            name='translated_entry',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='translated_meaning',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(to='api.translation'),
        ),
    ]
