# Generated by Django 5.1 on 2024-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_word_source_alter_translation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(default='', max_length=64),
        ),
    ]
