# Generated by Django 5.1 on 2024-08-19 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_word_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_at',
        ),
        migrations.AddField(
            model_name='word',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 8, 19, 12, 49, 20, 93508)),
        ),
    ]
