# Generated by Django 5.1 on 2024-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_entry_translation_translated_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='lang',
        ),
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.CharField(default='', max_length=2),
        ),
    ]
