# Generated by Django 5.1 on 2024-08-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_translation_lang_translation_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='translated_entry',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='translated_meaning',
            new_name='meaning',
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(default='RU', max_length=2),
        ),
    ]
