# Generated by Django 5.1 on 2024-08-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_translated_entry_translation_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('RU', 'Russian'), ('AZ', 'Azerbaijan')], max_length=2),
        ),
    ]
