# Generated by Django 5.1 on 2024-08-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_translation_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('az', 'Azerbaijani')], max_length=2),
        ),
    ]
