# Generated by Django 5.1 on 2024-09-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_translation_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
