# Generated by Django 5.1 on 2024-09-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_word_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='entry',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
